# Erorr Handling
```swift
var number = 0

enum MyError: Error{
	case invalidValue
	case outOfLimit
}

func square(width: Int, height: Int) throws -> Int{
	if width < 0 || height < 0{
		throw MyError.invalidValue
	}
	if width > 100 || height > 100{
		throw MyError.outOfLimit
	} 
	return width * height
}

//try문을 사용하려면 do-catch를 사용해야 한다.
do{
	try square(width: 50, height: 40) //throws 키워드가 있는 함수를 사용하려면 앞에 try를 붙여야 한다.
}catch{ //Error를 throw하고 catch함
	print(error) //error은 예약어 같은 느낌, 오류가 뜨면 오류를 띄워주는 역할
}

//오류가 나타났을때 nil값으로 처리하고 싶은 경우 try?를 사용한다.
try? square(width: -1, height: 40) //nil
```
```swift
func square(width: Int, height: Int) throws -> Int{
	if width < 0 || height < 0{
		throw MyError.invalidValue
	}
	if width > 100 || height > 100{
		throw MyError.outOfLimit
	} 
	return width * height
}

//rethrows는 파라미터에서 나온 에러만 처리
func area(completion: (Int, Int) throws -> Int) rethrows -> Int{
	try completion(50,40)
//이 안에서 또 thorw 쓰면 오류가 난다.
}

do{
	try area(completion: squareArea)
}catch{
	print(error)
}
```